# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0002_auto_20170509_1318'),
        ('scrolls', '0002_auto_20170508_2131'),
    ]

    operations = [
    ]
