# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0003_auto_20170514_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
