# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0005_note_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
