# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0006_auto_20170510_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.8751914271395516),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3185d07d-fe94-4891-a362-8b41dda511bb'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f20dd3fc-9879-459d-9b90-92d743ea19b8'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e91b3473-af0b-43b4-8af6-e8997d83c652'), editable=False, unique=True),
        ),
    ]
