# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:34
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('scrolls', '0011_auto_20170520_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='citation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scroll',
            name='citation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scrolls.User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.User'),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='scrolls.User'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='scrolls.User'),
        ),
    ]
