# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('scrolls', '0002_custom'),
    ]
    operations = [
        migrations.RunSQL(        
            [
                "DROP INDEX IF EXISTS event_ts_idx",
                "CREATE INDEX CONCURRENTLY event_ts_idx ON event USING gin(to_tsvector('english', title || ' ' || content_type || ' ' || coalesce(text,'')));",                
            ]
        )
    ]
