# Generated by Django 2.0.4 on 2018-04-30 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0005_auto_20180423_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('when_published', models.DateTimeField(null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='scrolls.User')),
            ],
            options={
                'db_table': 'notebook',
                'ordering': ['-when_modified'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['when_happened']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='in_event',
            new_name='with_event',
        ),
        migrations.RemoveField(
            model_name='note',
            name='in_scroll',
        ),
        migrations.AddField(
            model_name='note',
            name='uuid_next',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='note',
            name='in_notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Notebook'),
        ),
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together={('title', 'by_user')},
        ),
    ]
