# Generated by Django 2.0.4 on 2018-05-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0007_auto_20180510_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='with_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Event'),
        ),
    ]
