# Generated by Django 2.0.4 on 2018-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0008_auto_20180513_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid_next',
            field=models.UUIDField(blank=True, default=None),
        ),
    ]
