# Generated by Django 2.0.4 on 2018-05-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0010_auto_20180519_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uuid_next',
        ),
    ]
