# Generated by Django 2.0.4 on 2018-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0012_auto_20180521_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
