# Generated by Django 2.0.4 on 2018-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0013_auto_20180521_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_when',
            field=models.TextField(null=True),
        ),
    ]
