# Generated by Django 2.0.4 on 2018-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0015_auto_20180608_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(null=True), null=True, upload_to=None, width_field=models.IntegerField(null=True)),
        ),
    ]
