# Generated by Django 2.0.4 on 2018-06-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0018_auto_20180608_0404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('by_user', 'in_scroll', 'title', 'source_url')},
        ),
    ]
