# Generated by Django 2.0.4 on 2018-06-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0019_auto_20180608_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='original_when',
            new_name='when_original',
        ),
    ]
