# Generated by Django 2.0.4 on 2018-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0020_auto_20180608_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
