# Generated by Django 2.0.4 on 2018-06-12 20:24

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0023_auto_20180612_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
    ]
