# Generated by Django 2.0.4 on 2018-06-12 20:47

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0024_auto_20180612_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='citation',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
    ]
