# Generated by Django 2.0.4 on 2018-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0025_auto_20180612_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
