# Generated by Django 2.0.4 on 2018-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0026_auto_20180612_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
