# Generated by Django 2.0.4 on 2018-06-15 02:26

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0028_auto_20180612_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scroll',
            name='citation',
            field=django_bleach.models.BleachField(blank=True, default='true'),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='description',
            field=django_bleach.models.BleachField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='subtitle',
            field=django_bleach.models.BleachField(blank=True, default=''),
        ),
    ]
