# Generated by Django 2.0.4 on 2018-07-10 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0031_auto_20180707_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='following_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
