# Generated by Django 2.0.4 on 2018-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0032_note_following_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='following_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
