# Generated by Django 2.0.4 on 2018-07-20 01:31

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0033_auto_20180710_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='description',
            field=django_bleach.models.BleachField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='subtitle',
            field=django_bleach.models.BleachField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='citation',
            field=django_bleach.models.BleachField(blank=True, default=''),
        ),
    ]
