# Generated by Django 2.0.4 on 2018-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0034_auto_20180720_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-ranking', '?']},
        ),
        migrations.AddField(
            model_name='scroll',
            name='slug',
            field=models.SlugField(default='slhagxqcsoer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
