# Generated by Django 2.0.4 on 2018-08-02 16:57

from django.db import migrations, models
from django.utils.crypto import get_random_string

class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0035_auto_20180802_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scroll',
            name='slug',
            field=models.SlugField(default=get_random_string(12,'abcdefghijklmnopqrstuvwxyz')),
        ),
    ]
