# Generated by Django 2.0.4 on 2018-08-02 17:31

from django.db import migrations, models, transaction
from django.utils.crypto import get_random_string

class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0037_fix_slugs'),
    ]

    def gen_slug(apps, schema_editor):
        MyModel = apps.get_model('scrolls', 'Scroll')
        with transaction.atomic():
            for row in MyModel.objects.all():
                row.slug = get_random_string(12,'abcdefghijklmnopqrstuvwxyz')
                row.save()
    
    operations = [
        migrations.RunPython(gen_slug),
        migrations.AlterUniqueTogether(
            name='scroll',
            unique_together={('slug', 'by_user')},
        ),
    ]
