# Generated by Django 2.0.4 on 2018-08-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0038_auto_20180802_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scroll',
            name='slug',
            field=models.SlugField(default='tyhfrcslkskz'),
        ),
    ]
