# Generated by Django 2.0.4 on 2018-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0039_auto_20180802_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scroll',
            name='slug',
            field=models.SlugField(default='mzcbyqgdcrja'),
        ),
    ]
