# Generated by Django 2.0.4 on 2018-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0040_auto_20180817_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='meta_event_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
