# Generated by Django 2.0.4 on 2018-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0041_auto_20180818_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='meta_first_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scroll',
            name='meta_last_event',
            field=models.DateTimeField(null=True),
        ),
    ]
