# Generated by Django 2.0.4 on 2018-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0042_auto_20180819_1303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scroll',
            unique_together={('title', 'by_user')},
        ),
    ]
