# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('scrolls', '0001_initial'), ('scrolls', '0002_auto_20170509_1318'), ('scrolls', '0002_auto_20170508_2131'), ('scrolls', '0003_merge_20170510_1255'), ('scrolls', '0004_auto_20170510_1856'), ('scrolls', '0005_auto_20170510_1956'), ('scrolls', '0006_auto_20170510_1958'), ('scrolls', '0007_auto_20170510_1958'), ('scrolls', '0008_auto_20170511_0114')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(default='text/html', max_length=128)),
                ('content_type', models.CharField(default='event', max_length=128)),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('ranking', models.FloatField(db_index=True, default=0.3331160533142571)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('resolution', models.CharField(default='days', max_length=32)),
                ('source_url', models.URLField(null=True)),
                ('source_date', models.CharField(max_length=128, null=True)),
                ('content_url', models.URLField(max_length=512, null=True)),
            ],
            options={
                'ordering': ['-ranking', 'datetime'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=100000.0)),
                ('text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NoteMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, max_length=128)),
                ('media_file', models.FileField(upload_to=None)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scrolls.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=64, null=True, unique=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('image_location', models.CharField(max_length=128, null=True, unique=True)),
                ('source_url', models.URLField(max_length=512, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scroll',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='scrolls.Thumbnail'),
        ),
        migrations.AddField(
            model_name='scroll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='scroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Scroll'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='scroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scrolls.Scroll'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scrolls.Thumbnail'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scroll',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.5101268183682749),
        ),
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.5985936323716281),
        ),
        migrations.AddField(
            model_name='scroll',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.8680080552650092),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='scroll',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.34508990123398997),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.5055008262937107),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.8751914271395516),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.14407016638430536),
        ),
    ]
