# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mediatype', models.CharField(default='text/html', max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
                ('ranking', models.FloatField(db_index=True, default=0)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('resolution', models.CharField(default='days', max_length=32)),
                ('source_url', models.URLField(null=True)),
                ('source_date', models.CharField(max_length=128, null=True)),
                ('content_url', models.URLField(null=True)),
            ],
            options={
                'ordering': ['-ranking', 'datetime'],
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=0)),
                ('text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('display_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrolls.ContentType')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='NoteMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to=None)),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.MediaType')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scrolls.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='scroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scrolls.Scroll'),
        ),
    ]
