# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('identifier', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('image', models.FileField(upload_to=None)),
                ('source_url', models.URLField(null=True)),
                ('source_date', models.CharField(max_length=128, null=True)),
                ('content_url', models.URLField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('identifier', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField()),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('display_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.ContentType')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.Event')),
            ],
        ),
        migrations.CreateModel(
            name='NoteMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to=None)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.MediaType')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='scroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.Scroll'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.MediaType'),
        ),
        migrations.AddField(
            model_name='event',
            name='scroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrolls.Scroll'),
        ),
    ]
