# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0001_initial'),
    ]
    operations = [
        migrations.RunSQL(        
            "CREATE INDEX scroll_ts_idx ON scroll USING gin(to_tsvector('english', title || ' ' || subtitle || ' ' || description)); ",
            "CREATE INDEX event_ts_idx ON event USING gin(to_tsvector('english', title || ' ' || text));",
        )
    ]
