# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='note',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='notemedia',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='uuid',
        ),
    ]
