# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.5985936323716281),
        ),
    ]
