# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0002_auto_20170227_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='media_type',
        ),
        migrations.AddField(
            model_name='event',
            name='mediatype',
            field=models.CharField(default='text/html', max_length=128),
        ),
    ]
