# Generated by Django 2.0.4 on 2018-04-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0003_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='with_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='scrolls.Thumbnail'),
        ),
    ]
