# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0003_merge_20170510_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.8680080552650092),
        ),
    ]
