# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0003_auto_20170227_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
