# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrolls', '0003_auto_20170421_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=64)),
                ('image_url', models.URLField(max_length=512, null=True)),
                ('source_url', models.URLField(max_length=512, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scrolls.Thumbnail'),
        ),
    ]
