# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0004_remove_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
