# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0004_auto_20170514_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='kind',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
