# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0004_auto_20170421_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
