# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0005_auto_20170301_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mediatype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='scroll',
        ),
        migrations.AddField(
            model_name='scroll',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrolls.Event'),
        ),
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='title',
            field=models.TextField(),
        ),
    ]
