# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0005_auto_20170510_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.FloatField(db_index=True, default=0.5055008262937107),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('22d6b26b-bf01-4402-bbf5-d497801880c2'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('078bc3ea-79eb-4f12-9ed2-4b3e2e0e78b1'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('09e27c92-c45d-407c-974e-b8376f2efc47'), editable=False, unique=True),
        ),
    ]
