# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0006_auto_20170422_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
