# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0007_auto_20170422_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='image_url',
            new_name='image_location',
        ),
    ]
