# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0007_auto_20170304_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ranking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
