# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0008_auto_20170422_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_location',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='sha1',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='source_url',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL),
        ),
    ]
