# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0008_auto_20170515_0131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([]),
        ),
    ]
