# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0009_auto_20170515_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
