# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0010_auto_20170422_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL),
        ),
    ]
