# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0010_auto_20170305_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='display_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrolls.ContentType'),
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrolls.Event'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notemedia',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scrolls.Note'),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to=settings.AUTH_USER_MODEL),
        ),
    ]
