# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0011_auto_20170422_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='scrolls.Thumbnail'),
        ),
    ]
