# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0012_scroll_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mediatype',
            new_name='media_type',
        ),
    ]
