# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0012_auto_20170409_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resolution',
            field=models.CharField(default='days', max_length=32),
        ),
    ]
