# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0012_auto_20170523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='fiction',
            field=models.BooleanField(default=False),
        ),
    ]
