# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrolls', '0013_auto_20170424_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scroll',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
